### ISSUE TITLE
Failing on installing pyqtwebengine (due to M1?)

### ISSUE THREAD

**Issue by matteha** [emacs-eaf/emacs-application-framework#868] opened 2021-11-04 17:50 UTC
I'm trying to get eaf running on an M1 Macbook but I am stuck on the "install-eaf.py" where it'll hang on trying to install PyQTWebEngine 5:

[EAF] Running pip install epc pyqt5 pyqt5-sip pyqtwebengine mac-app-frontmost @ /Users/admin/.emacs.d/.local/straight/repos/emacs-application-framework
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting epc
  Using cached epc-0.0.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyqt5 in /opt/homebrew/lib/python3.9/site-packages (5.15.4)
Requirement already satisfied: pyqt5-sip in /opt/homebrew/lib/python3.9/site-packages (12.9.0)
Collecting pyqtwebengine
  Using cached PyQtWebEngine-5.15.5.tar.gz (48 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/pr/f8cy839n3xjdprp2d2x_v48h0000gn/T/tmphwzu2127
       cwd: /private/var/folders/pr/f8cy839n3xjdprp2d2x_v48h0000gn/T/pip-install-xfnl65y2/pyqtwebengine_e2e1133566d44bef9a88906be3da7469
  Complete output (6 lines):
  Querying qmake about your Qt installation...
  /opt/homebrew/bin/qmake -query
  These bindings will be built: QtWebEngineCore, QtWebEngine, QtWebEngineWidgets.
  Generating the QtWebEngineCore bindings...
  _in_process.py: Unable to find file "QtCore/QtCoremod.sip"
  
I have a feeling this has to due with being on M1 but I am not sure. Would you have any insight into this or a possible workaround? (I installed pyqt5 via brew which has it patched for M1:
brew install pyqt@5, on python 3.9). 

Thank you!

**Comment by manateelazycat** [comment] 2021-11-05 01:10
Looks file QtCore/QtCoremod.sip is miss in your environment, I suggest you need make sure PyQt5 is install complete.
It's nothing to workaround.

I haven't macOS, sorry I can't help you. :(

**Comment by ijoseph** [comment] 2021-11-14 21:03
Also running into this. Managed to get `PyQT5` itself installed with homebrew, but agreed that inability to install the `pyqtwebengine` package the issue[^1], probably because the wheels don't support `arm64` on `macOS`. 

I downloaded the source `PyQtWebEngine-5.15.5.tar.gz` from [PyPI](https://pypi.org/project/PyQtWebEngine/#files), but it's not immediately clear how to install/ compile it. 

```bash
❯ /opt/homebrew/bin/python3 configure.py
Error: Make sure you have a working sip on your PATH or use the --sip argument
to explicitly specify a working sip.
```

After `brew install`-ing `sip`, it created nothing called `sip` per se, but: 
```bash
❯ tree /opt/homebrew/Cellar/sip/6.4.0/bin
/opt/homebrew/Cellar/sip/6.4.0/bin
├── sip-build
├── sip-distinfo
├── sip-install
├── sip-module
├── sip-sdist
└── sip-wheel
```
None of which really seems to work when passed in as `--sip` to `configure.py`[^2]. I suspect this is because `sip` version is now too new (has a different API) to be able to compile `PyQTWebEngine-5.*`

So next steps appear to be to see whether we can either install an older version of `sip`, or force `PyQTWebEngine-5.*`'s `configure.py` to work with the new `sip` API. 

[^1]: 
        /opt/homebrew/bin/python3 -m pip install pyqtwebengine
        DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
        Collecting pyqtwebengine
          Using cached PyQtWebEngine-5.15.5.tar.gz (48 kB)
          Installing build dependencies ... done
          Getting requirements to build wheel ... done
          Preparing metadata (pyproject.toml) ... error
          ERROR: Command errored out with exit status 1:
           command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/2v/gh8jsshx2fz2cr8mny4qfm480000gn/T/tmpfns1z29c
               cwd: /private/var/folders/2v/gh8jsshx2fz2cr8mny4qfm480000gn/T/pip-install-u2drec0s/pyqtwebengine_ee872ea93c104005ae9cf611e9c766eb
          Complete output (6 lines):
          Querying qmake about your Qt installation...
          /opt/homebrew/bin/qmake -query
          These bindings will be built: QtWebEngineCore, QtWebEngine, QtWebEngineWidgets.
          Generating the QtWebEngineCore bindings...
          _in_process.py: Unable to find file "QtCore/QtCoremod.sip"   

[^2]: 
         ❯ /opt/homebrew/bin/python3 configure.py --sip=/opt/homebrew/Cellar/sip/6.4.0/bin/sip-module
        Installing sip.h in
        /Users/isaacjoseph/Code/Projects/EAF/PyQtWebEngine-5.15.5/include...
        Configuring PyQtWebEngine 5.15.5...
        The PyQtWebEngine .sip files will be installed in
        /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PyQt5/bindings.
        PyQtWebEngine will be installed in
        /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PyQt5.
        PyQt 5.15.4 is being used.
        Qt 5.15.2 is being used.
        sip 6.4.0 is being used.
        The sip executable is /opt/homebrew/Cellar/sip/6.4.0/bin/sip-module.
        PyQtWebEngine is being built with 'protected' redefined as 'public'.
        The PEP 484 stubs will be installed in
        /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PyQt5.
        The QScintilla API file will be installed in
        /opt/homebrew/share/qt/qsci/api/python.
        Generating the C++ source for the QtWebEngine module...
        Error: Unable to create the C++ code.

**Comment by tears330** [comment] 2021-12-11 16:41
I got the same problem. At first I try to use `brew install pyqt5` to install the binary for arm.  But they don't provide the `PyQtWebEngine`. 
So I try to use Rosetta2 run the python process
```sh
arch -x86_64 python3 ./install-eaf.py
```
It will compile the x86 binary for qt library. Then I got an error on *eaf* buffer about the python process try to load the arm version binary. So I find the source code about start the python process:

https://github.com/emacs-eaf/emacs-application-framework/blob/master/eaf.el#L604-L606

It will start the python process for arm version on my m1 mac, so just replace the `start_process` params to `arch -x86_64`, the python process will run on x86 version. Here is my code:

```elisp
(apply 'start-process
                     eaf-name eaf-name
                     "arch" (append (list "-x86_64" eaf-internal-process-prog) eaf-internal-process-args))
```

It's working will on my m1 macbook pro :)

![image](https://user-images.githubusercontent.com/8414017/145684518-2bc101db-2ed6-4a40-989d-9f970ea24775.png)

**Comment by ijoseph** [comment] 2021-12-11 18:20
Nicely-done. Is the performance ok?

Would be nice to not have to emulate the intel architecture, but not as nice as being able to use this without putting in weeks of effort chasing down the incompatibilities I suppose.

**Comment by manateelazycat** [comment] 2021-12-12 00:59
> I got the same problem. At first I try to use `brew install pyqt5` to install the binary for arm. But they don't provide the `PyQtWebEngine`. So I try to use Rosetta2 run the python process
> 
> ```shell
> arch -x86_64 python3 ./install-eaf.py
> ```
> 
> It will compile the x86 binary for qt library. Then I got an error on _eaf_ buffer about the python process try to load the arm version binary. So I find the source code about start the python process:
> 
> https://github.com/emacs-eaf/emacs-application-framework/blob/master/eaf.el#L604-L606
> 
> It will start the python process for arm version on my m1 mac, so just replace the `start_process` params to `arch -x86_64`, the python process will run on x86 version. Here is my code:
> 
> ```emacs-lisp
> (apply 'start-process
>                      eaf-name eaf-name
>                      "arch" (append (list "-x86_64" eaf-internal-process-prog) eaf-internal-process-args))
> ```
> 
> It's working well on my m1 macbook pro :)
> 
> ![image](https://user-images.githubusercontent.com/8414017/145684518-2bc101db-2ed6-4a40-989d-9f970ea24775.png)

can you give me a patch? thanks

**Comment by tears330** [comment] 2021-12-12 09:58
https://github.com/emacs-eaf/emacs-application-framework/pull/892

**Comment by tears330** [comment] 2021-12-12 10:04
> Nicely-done. Is the performance ok?
> 
> Would be nice to not have to emulate the intel architecture, but not as nice as being able to use this without putting in weeks of effort chasing down the incompatibilities I suppose.

It's work very well on my M1 MacBook Pro. The problem is using Rosetta2 to emulate the intel architecture will lose a little battery life 😅. 

I'm not pro as cpp so I just give up compile the PyQtEngine. Life is short bro 😜

**Comment by manateelazycat** [comment] 2021-12-12 22:52
> > Nicely-done. Is the performance ok?
> > Would be nice to not have to emulate the intel architecture, but not as nice as being able to use this without putting in weeks of effort chasing down the incompatibilities I suppose.
> 
> It's work very well on my M1 MacBook Pro. The problem is using Rosetta2 to emulate the intel architecture will lose a little battery life 😅.
> 
> I'm not pro as cpp so I just give up compile the PyQtEngine. Life is short bro 😜

cool，thanks for parch

**Closed by manateelazycat** 2021-12-12 22:52 UTC

**Comment by ckmufeng** [comment] 2022-11-17 08:32
Success on M1 mac with Master。
1. default install；
2. pip uninstall PyQtWebEngine. (which maybe 5.15x)
3. pip install pyside6==6.3.1
4. pip install PyQt6-WebEngine
5. set QT_QPA_PLATFORM_PLUGIN_PATH to your_envdir/site-packages//PySide6/Qt/plugins/platforms
6. remove any reduntant lib like this
```
qt.core.plugin.loader: In /Users/ck/miniconda3/envs/py38/plugins/platforms/libqcocoa.dylib:
Plugin uses incompatible Qt library (5.15.0) [release]
```

Result:
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/16316378/202396003-9b73cd44-abe6-4b20-beb1-bce3a5cfcaf6.png">

**Comment by hasnolen** [comment] 2022-11-18 06:30
> Result:

Nice. 

Unfortunately, `eaf-browser` works [^2] for me on M1[^1] , but not what I actually wanted to use, [eaf-markdown-previewer](https://github.com/emacs-eaf/eaf-markdown-previewer): 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/95154022/202635992-5cdfaf60-2e5c-471a-aab7-462635a15396.png">, which shows a blank preview pane. 

Any ideas? This degenerate thing is what `eaf-demo` shows me: 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/95154022/202636150-b9385d23-2d1e-46f3-aeb1-651af8c893d3.png">
 
 

[^1]: with `Python 3.10.5`  and 
      > ```bash
      > PyQt6==6.3.1
      > PyQt6-Qt6==6.3.1
      > PyQt6-sip==13.4.0
      > PyQt6-WebEngine==6.3.1
      > PyQt6-WebEngine-Qt6==6.3.1
      > ```

[^2]: <img width="200" alt="image" src="https://user-images.githubusercontent.com/95154022/202635765-39a327e3-3eaf-43b8-890b-97c7717abe53.png">
